name: Build Whitehole

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name : Checkout Repo
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Ant Cache
      id: ant
      uses: actions/cache@v2.1.6
      with:
        path: C:\ProgramData\chocolatey\bin\ant.exe
        key: ${{ runner.os }}-ant
    - name: Install Apache Ant
      run: choco install ant --acceptlicense --confirm --verbose
      shell: cmd
    - name: Curl Cache
      id: curl
      uses: actions/cache@v2.1.6
      with:
        path: C:\ProgramData\chocolatey\bin\curl.exe
        key: ${{ runner.os }}-curl
    - name: Install cURL
      if: steps.curl.outputs.cache-hit != 'true'
      run: choco install curl --acceptlicense --confirm --verbose
      shell: cmd
    - name: Build Whitehole
      run: Build.cmd
      shell: cmd
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: "Build.zip"
    - name: Make a release
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "auto"
        prerelease: true
        title: "Auto Build"
        files: |
          Build.zip
